"""create ketl models

Revision ID: 097a72ba1416
Revises: 
Create Date: 2021-02-10 09:50:12.328439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '097a72ba1416'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ketl_api_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ketl_api_config_description'), 'ketl_api_config', ['description'], unique=False)
    op.create_index(op.f('ix_ketl_api_config_name'), 'ketl_api_config', ['name'], unique=True)
    op.create_table('ketl_creds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_config_id', sa.Integer(), nullable=True),
    sa.Column('creds_details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['ketl_api_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ketl_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('data_dir', sa.String(), nullable=True),
    sa.Column('api_config_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['ketl_api_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url', 'data_dir', 'api_config_id')
    )
    op.create_index(op.f('ix_ketl_source_base_url'), 'ketl_source', ['base_url'], unique=False)
    op.create_index(op.f('ix_ketl_source_data_dir'), 'ketl_source', ['data_dir'], unique=False)
    op.create_index(op.f('ix_ketl_source_source_type'), 'ketl_source', ['source_type'], unique=False)
    op.create_table('ketl_cached_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('url_params', sa.JSON(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('last_download', sa.DateTime(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('refresh_interval', sa.Interval(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('cache_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_archive', sa.Boolean(), nullable=True),
    sa.Column('extract_to', sa.String(), nullable=True),
    sa.Column('expected_mode', sa.Enum('auto', 'explicit', 'self', name='expectedmode'), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['ketl_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'url', 'path')
    )
    op.create_index(op.f('ix_ketl_cached_file_cache_type'), 'ketl_cached_file', ['cache_type'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_expected_mode'), 'ketl_cached_file', ['expected_mode'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_extract_to'), 'ketl_cached_file', ['extract_to'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_is_archive'), 'ketl_cached_file', ['is_archive'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_last_download'), 'ketl_cached_file', ['last_download'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_last_update'), 'ketl_cached_file', ['last_update'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_path'), 'ketl_cached_file', ['path'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_refresh_interval'), 'ketl_cached_file', ['refresh_interval'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_size'), 'ketl_cached_file', ['size'], unique=False)
    op.create_index(op.f('ix_ketl_cached_file_url'), 'ketl_cached_file', ['url'], unique=False)
    op.create_table('ketl_expected_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('hash', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('cached_file_id', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('last_processed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cached_file_id'], ['ketl_cached_file.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path', 'cached_file_id')
    )
    op.create_index(op.f('ix_ketl_expected_file_file_type'), 'ketl_expected_file', ['file_type'], unique=False)
    op.create_index(op.f('ix_ketl_expected_file_last_processed'), 'ketl_expected_file', ['last_processed'], unique=False)
    op.create_index(op.f('ix_ketl_expected_file_path'), 'ketl_expected_file', ['path'], unique=False)
    op.create_index(op.f('ix_ketl_expected_file_processed'), 'ketl_expected_file', ['processed'], unique=False)
    op.create_index(op.f('ix_ketl_expected_file_size'), 'ketl_expected_file', ['size'], unique=False)
    op.drop_index('ix_source_base_url', table_name='source')
    op.drop_index('ix_source_data_dir', table_name='source')
    op.drop_index('ix_source_source_type', table_name='source')
    op.drop_table('source')
    op.drop_index('ix_cached_file_cache_type', table_name='cached_file')
    op.drop_index('ix_cached_file_expected_mode', table_name='cached_file')
    op.drop_index('ix_cached_file_extract_to', table_name='cached_file')
    op.drop_index('ix_cached_file_is_archive', table_name='cached_file')
    op.drop_index('ix_cached_file_last_download', table_name='cached_file')
    op.drop_index('ix_cached_file_last_update', table_name='cached_file')
    op.drop_index('ix_cached_file_meta', table_name='cached_file')
    op.drop_index('ix_cached_file_path', table_name='cached_file')
    op.drop_index('ix_cached_file_refresh_interval', table_name='cached_file')
    op.drop_index('ix_cached_file_size', table_name='cached_file')
    op.drop_index('ix_cached_file_url', table_name='cached_file')
    op.drop_table('cached_file')
    op.drop_index('ix_expected_file_path', table_name='expected_file')
    op.drop_table('expected_file')
    op.drop_table('creds')
    op.drop_table('test_table')
    op.drop_index('ix_api_config_name', table_name='api_config')
    op.drop_table('api_config')
    op.drop_index('ix_file_cache_cache_type', table_name='file_cache')
    op.drop_index('ix_file_cache_last_download', table_name='file_cache')
    op.drop_index('ix_file_cache_last_update', table_name='file_cache')
    op.drop_index('ix_file_cache_path', table_name='file_cache')
    op.drop_index('ix_file_cache_size', table_name='file_cache')
    op.drop_index('ix_file_cache_url', table_name='file_cache')
    op.drop_table('file_cache')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('url_params', sqlite.JSON(), nullable=True),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('last_download', sa.DATETIME(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.Column('hash', sa.VARCHAR(), nullable=True),
    sa.Column('cache_type', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_file_cache_url', 'file_cache', ['url'], unique=False)
    op.create_index('ix_file_cache_size', 'file_cache', ['size'], unique=False)
    op.create_index('ix_file_cache_path', 'file_cache', ['path'], unique=False)
    op.create_index('ix_file_cache_last_update', 'file_cache', ['last_update'], unique=False)
    op.create_index('ix_file_cache_last_download', 'file_cache', ['last_download'], unique=False)
    op.create_index('ix_file_cache_cache_type', 'file_cache', ['cache_type'], unique=False)
    op.create_table('api_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('hash', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_config_name', 'api_config', ['name'], unique=False)
    op.create_table('test_table',
    sa.Column('x', sa.INTEGER(), nullable=True),
    sa.Column('y', sa.INTEGER(), nullable=True),
    sa.Column('z', sa.INTEGER(), nullable=True)
    )
    op.create_table('creds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('api_config_id', sa.INTEGER(), nullable=True),
    sa.Column('creds_details', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expected_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expected_file_path', 'expected_file', ['path'], unique=False)
    op.create_table('cached_file',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('url_params', sqlite.JSON(), nullable=True),
    sa.Column('path', sa.VARCHAR(), nullable=True),
    sa.Column('last_download', sa.DATETIME(), nullable=True),
    sa.Column('last_update', sa.DATETIME(), nullable=True),
    sa.Column('refresh_interval', sa.DATETIME(), nullable=True),
    sa.Column('hash', sa.VARCHAR(), nullable=True),
    sa.Column('cache_type', sa.VARCHAR(), nullable=True),
    sa.Column('size', sa.INTEGER(), nullable=True),
    sa.Column('is_archive', sa.BOOLEAN(), nullable=True),
    sa.Column('extract_to', sa.VARCHAR(), nullable=True),
    sa.Column('expected_mode', sa.VARCHAR(length=8), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.CheckConstraint("expected_mode IN ('auto', 'explicit')", name='expectedmode'),
    sa.CheckConstraint('is_archive IN (0, 1)'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cached_file_url', 'cached_file', ['url'], unique=False)
    op.create_index('ix_cached_file_size', 'cached_file', ['size'], unique=False)
    op.create_index('ix_cached_file_refresh_interval', 'cached_file', ['refresh_interval'], unique=False)
    op.create_index('ix_cached_file_path', 'cached_file', ['path'], unique=False)
    op.create_index('ix_cached_file_meta', 'cached_file', ['meta'], unique=False)
    op.create_index('ix_cached_file_last_update', 'cached_file', ['last_update'], unique=False)
    op.create_index('ix_cached_file_last_download', 'cached_file', ['last_download'], unique=False)
    op.create_index('ix_cached_file_is_archive', 'cached_file', ['is_archive'], unique=False)
    op.create_index('ix_cached_file_extract_to', 'cached_file', ['extract_to'], unique=False)
    op.create_index('ix_cached_file_expected_mode', 'cached_file', ['expected_mode'], unique=False)
    op.create_index('ix_cached_file_cache_type', 'cached_file', ['cache_type'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('source_type', sa.VARCHAR(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(), nullable=True),
    sa.Column('data_dir', sa.VARCHAR(), nullable=True),
    sa.Column('api_config_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['api_config_id'], ['api_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_source_type', 'source', ['source_type'], unique=False)
    op.create_index('ix_source_data_dir', 'source', ['data_dir'], unique=False)
    op.create_index('ix_source_base_url', 'source', ['base_url'], unique=False)
    op.drop_index(op.f('ix_ketl_expected_file_size'), table_name='ketl_expected_file')
    op.drop_index(op.f('ix_ketl_expected_file_processed'), table_name='ketl_expected_file')
    op.drop_index(op.f('ix_ketl_expected_file_path'), table_name='ketl_expected_file')
    op.drop_index(op.f('ix_ketl_expected_file_last_processed'), table_name='ketl_expected_file')
    op.drop_index(op.f('ix_ketl_expected_file_file_type'), table_name='ketl_expected_file')
    op.drop_table('ketl_expected_file')
    op.drop_index(op.f('ix_ketl_cached_file_url'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_size'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_refresh_interval'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_path'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_last_update'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_last_download'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_is_archive'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_extract_to'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_expected_mode'), table_name='ketl_cached_file')
    op.drop_index(op.f('ix_ketl_cached_file_cache_type'), table_name='ketl_cached_file')
    op.drop_table('ketl_cached_file')
    op.drop_index(op.f('ix_ketl_source_source_type'), table_name='ketl_source')
    op.drop_index(op.f('ix_ketl_source_data_dir'), table_name='ketl_source')
    op.drop_index(op.f('ix_ketl_source_base_url'), table_name='ketl_source')
    op.drop_table('ketl_source')
    op.drop_table('ketl_creds')
    op.drop_index(op.f('ix_ketl_api_config_name'), table_name='ketl_api_config')
    op.drop_index(op.f('ix_ketl_api_config_description'), table_name='ketl_api_config')
    op.drop_table('ketl_api_config')
    # ### end Alembic commands ###
